# TASK 6:Combine all 3 into one Knowledge Base

In [ ]:
import sys
!{sys.executable} -m pip install kagglehub pandas

In [2]:
import sys
print(sys.executable)

C:\Users\famil\anaconda3\python.exe

In [4]:
import kagglehub
import pandas as pd
print("All good, ready to go!")

All good, ready to go!

In [ ]:
import kagglehub

# Download the full dataset (it's small - ~72MB total)
path = kagglehub.dataset_download("saurabhshahane/long-lived-bug-prediction")
print("Dataset downloaded to:", path)

In [15]:
'''import pandas as pd
mozilla_df = pd.read_csv(".../AI_Smart_Bug_Analyzer_-_Fix-_Advisor-/data/mozilla_bug_report_data.csv/mozilla_bug_report_data.csv")
eclipse_df = pd.read_csv(".../AI_Smart_Bug_Analyzer_-_Fix-_Advisor-/data/eclipse_bug_report_data.csv/eclipse_bug_report_data.csv")
print(mozilla_df.shape)
print(eclipse_df.shape)

print(mozilla_df.head())

print( eclipse_df.head())'''




import pandas as pd
mozilla_df = pd.read_csv("C:/Users/famil/OneDrive/Desktop/AI_Smart_Bug_Analyzer_-_Fix-_Advisor-/data/mozilla_bug_report_data.csv/mozilla_bug_report_data.csv")
eclipse_df = pd.read_csv("C:/Users/famil/OneDrive/Desktop/AI_Smart_Bug_Analyzer_-_Fix-_Advisor-/data/eclipse_bug_report_data.csv/eclipse_bug_report_data.csv")
print(mozilla_df.shape)
print(eclipse_df.shape)

mozilla_df.head()

(9999, 19)
(9776, 19)

,bug_id,creation_date,component_name,product_name,short_description,long_description,assignee_name,reporter_name,resolution_category,resolution_code,status_category,status_code,update_date,quantity_of_votes,quantity_of_comments,resolution_date,bug_fix_time,severity_category,severity_code
0,BUGZILLA-294734,2005-05-18,Bugzilla-General,BUGZILLA,Emergency 2.16.10 Release,2.16.9 is broken -- many users can't enter bug...,mkanat,mkanat,fixed,1,resolved,4,2005-05-19,0,15,2005-05-19,1,blocker,6
1,OTHER_APPLICATIONS-363323,2006-12-09,DOM Inspector,OTHER_APPLICATIONS,DOM View is really inefficient with setting wh...,From comment in url:\n\nCurrent code:\nmenuite...,sdwilsh,sdwilsh,fixed,1,resolved,4,2011-06-01,0,8,2007-01-14,36,normal,2
2,SUPPORT.MOZILLA.ORG-398246,2007-10-02,General,SUPPORT.MOZILLA.ORG,Add support for custom cookies and cache headers,Adding support for custom headers and cookie n...,morgamic,morgamic,fixed,1,resolved,4,2009-11-02,0,23,2008-03-24,174,blocker,6
3,RELEASE_ENGINEERING-525991,2009-11-02,General,RELEASE_ENGINEERING,Create Major Update from 3.0.15 to 3.5.5,NaN,catlee,catlee,fixed,1,resolved,4,2013-08-12,0,7,2009-11-10,8,normal,2
4,OTHER_APPLICATIONS-318859,2005-12-02,ChatZilla,OTHER_APPLICATIONS,DCC functionality in ChatZilla isn't functional.,User-Agent: Mozilla/5.0 (Macintosh U PPC...,gijskruitbosch+bugs,dafydd,fixed,1,resolved,4,2006-02-10,0,14,2005-12-07,5,normal,2

In [2]:
import pandas as pd
apache_df = pd.read_csv(r"D:/issues.csv", nrows=10000)
print(apache_df.shape)
apache_df.head()
apache_df.to_csv(r"D:/processed_issues.csv", index=False)

#apache_df.describe()

(10000, 37)

In [16]:
print(mozilla_df.columns)
print(eclipse_df.columns)
print(apache_df.columns)

print('\n\n\n')

mozilla_df.head(10)

Index(['bug_id', 'creation_date', 'component_name', 'product_name',
       'short_description', 'long_description', 'assignee_name',
       'reporter_name', 'resolution_category', 'resolution_code',
       'status_category', 'status_code', 'update_date', 'quantity_of_votes',
       'quantity_of_comments', 'resolution_date', 'bug_fix_time',
       'severity_category', 'severity_code'],
      dtype='str')
Index(['bug_id', 'creation_date', 'component_name', 'product_name',
       'short_description', 'long_description', 'assignee_name',
       'reporter_name', 'resolution_category', 'resolution_code',
       'status_category', 'status_code', 'update_date', 'quantity_of_votes',
       'quantity_of_comments', 'resolution_date', 'bug_fix_time',
       'severity_category', 'severity_code'],
      dtype='str')
Index(['id', 'key', 'summary', 'resolution.id', 'resolution.description',
       'resolution.name', 'priority.id', 'priority.name', 'labels', 'assignee',
       'status.id', 'status.description', 'status.name', 'statusCategory.id',
       'statusCategory.key', 'statusCategory.colorName', 'statusCategory.name',
       'customfield_12310921', 'creator', 'subtasks', 'reporter',
       'votes.votes', 'issuetype.id', 'issuetype.description',
       'issuetype.name', 'issuetype.subtask', 'project.id', 'project.key',
       'project.name', 'projectCategory.id', 'projectCategory.description',
       'projectCategory.name', 'resolutiondate', 'watches.watchCount',
       'created', 'updated', 'description'],
      dtype='str')

,bug_id,creation_date,component_name,product_name,short_description,long_description,assignee_name,reporter_name,resolution_category,resolution_code,status_category,status_code,update_date,quantity_of_votes,quantity_of_comments,resolution_date,bug_fix_time,severity_category,severity_code
0,BUGZILLA-294734,2005-05-18,Bugzilla-General,BUGZILLA,Emergency 2.16.10 Release,2.16.9 is broken -- many users can't enter bug...,mkanat,mkanat,fixed,1,resolved,4,2005-05-19,0,15,2005-05-19,1,blocker,6
1,OTHER_APPLICATIONS-363323,2006-12-09,DOM Inspector,OTHER_APPLICATIONS,DOM View is really inefficient with setting wh...,From comment in url:\n\nCurrent code:\nmenuite...,sdwilsh,sdwilsh,fixed,1,resolved,4,2011-06-01,0,8,2007-01-14,36,normal,2
2,SUPPORT.MOZILLA.ORG-398246,2007-10-02,General,SUPPORT.MOZILLA.ORG,Add support for custom cookies and cache headers,Adding support for custom headers and cookie n...,morgamic,morgamic,fixed,1,resolved,4,2009-11-02,0,23,2008-03-24,174,blocker,6
3,RELEASE_ENGINEERING-525991,2009-11-02,General,RELEASE_ENGINEERING,Create Major Update from 3.0.15 to 3.5.5,NaN,catlee,catlee,fixed,1,resolved,4,2013-08-12,0,7,2009-11-10,8,normal,2
4,OTHER_APPLICATIONS-318859,2005-12-02,ChatZilla,OTHER_APPLICATIONS,DCC functionality in ChatZilla isn't functional.,User-Agent: Mozilla/5.0 (Macintosh U PPC...,gijskruitbosch+bugs,dafydd,fixed,1,resolved,4,2006-02-10,0,14,2005-12-07,5,normal,2
5,DEVELOPER.MOZILLA.ORG-416840,2008-02-11,General,DEVELOPER.MOZILLA.ORG,Fix and cruft,Since we removed the breadcrumbs and title-ove...,nobody,jorendorff,fixed,1,resolved,4,2012-09-18,0,4,2008-02-12,1,normal,2
6,MARKETPLACE_GRAVEYARD-977729,2014-02-27,Reviewer Tools,MARKETPLACE_GRAVEYARD,add a waffle to disable the theme queue,This is a pretty private URL so literally putt...,kngo,wclouser,fixed,1,resolved,4,2014-03-26,0,2,2014-03-13,14,normal,2
7,THUNDERBIRD-339875,2006-05-31,Build Config,THUNDERBIRD,ship ga-IE for 1.5.0.5,the ga-IE locale for Thunderbird 1.5 has owner...,rhelmer,mscott,fixed,1,resolved,4,2006-07-19,0,12,2006-06-26,26,normal,2
8,FIREFOX-420556,2008-03-02,Theme,FIREFOX,sidebarheader on GNOME has a transparent backg...,Created attachment 306847\npatch v1: fixes pro...,myk,myk,fixed,1,resolved,4,2008-03-12,0,6,2008-03-05,3,normal,2
9,MOZILLA_LOCALIZATIONS-415621,2008-02-04,mk / Macedonian,MOZILLA_LOCALIZATIONS,Firefox 3 mk release tracker,This is a tracker bug for releasing Firefox 3 ...,nobody,l10n,fixed,1,resolved,4,2008-07-15,0,2,2008-07-15,162,normal,2

In [17]:
eclipse_df.head(10)

,bug_id,creation_date,component_name,product_name,short_description,long_description,assignee_name,reporter_name,resolution_category,resolution_code,status_category,status_code,update_date,quantity_of_votes,quantity_of_comments,resolution_date,bug_fix_time,severity_category,severity_code
0,RECOMMENDERS-467951,2015-05-22,Core,RECOMMENDERS,LogTraceException in ProposalUtils.toMethodNam...,The following incident was reported via the au...,recommenders-inbox,error-reports-inbox,fixed,1,closed,6,2015-05-27,0,2,2015-05-27,5,normal,2
1,QVTO-463396,2015-03-29,Engine,QVTO,CCE in DecorationNodeImpl.eSet (159),The following incident was reported via the au...,serg.boyko2011,error-reports-inbox,fixed,1,resolved,4,2015-04-01,0,8,2015-03-31,2,normal,2
2,EQUINOX-530069,2018-01-20,Compendium,EQUINOX,[http servlet] During dispatching javax.servle...,Original issue https://issues.liferay.com/brow...,raymond.auge,raymond.auge,fixed,1,resolved,4,2018-01-22,0,3,2018-01-22,2,normal,2
3,NATTABLE-422482,2013-11-25,Core,NATTABLE,Left border of NatTable is not drawn,Rendering a NatTable on a Composite with margi...,dirk.fauth,dirk.fauth,fixed,1,closed,6,2014-07-23,0,3,2013-11-25,0,normal,2
4,WTP_JAVA_EE_TOOLS-116294,2005-11-14,jst.j2ee,WTP_JAVA_EE_TOOLS,NPE while importing EAR with utility jar,Import and EAR which has EJb and Ejb client tr...,jsholl,nagrawal,fixed,1,closed,6,2005-12-09,0,4,2005-11-15,1,blocker,6
5,PDT-165702,2006-11-23,Code Assist,PDT,No Items in Outline/PHP Project Outline (Repro...,Using\n\norg.eclipse.php_feature (0.7.0.v20061...,guy.g,mickey,fixed,1,closed,6,2006-12-03,0,5,2006-12-03,10,normal,2
6,WTP_SOURCE_EDITING-103608,2005-07-13,wst.html,WTP_SOURCE_EDITING,Error in setting disabled attribute,1. Open an HTML file\n2. Type the tag.\n3. Se...,nitind,kvenugopal,fixed,1,resolved,4,2007-08-29,0,3,2007-08-29,777,trivial,1
7,JDT-84477,2005-02-04,UI,JDT,[refactoring] Lose comments when refactoring,build i0202\n\nHere is a test case in which yo...,jdt-ui-inbox,dj.houghton,fixed,1,resolved,4,2005-02-07,0,2,2005-02-07,3,normal,2
8,BIRT-236012,2008-06-06,Report Engine,BIRT,[Regression] There are two extra lines when pr...,Created attachment 103916\nreport design\n\nDe...,hustlg,xwang,fixed,1,closed,6,2009-09-08,0,4,2008-06-08,2,normal,2
9,SUBVERSIVE-264685,2009-02-12,UI,SUBVERSIVE,Share Project Wizard dialog typo,Created attachment 125521\nscreen shot of dial...,igor.burilo,mikecepek,fixed,1,resolved,4,2009-10-05,0,2,2009-10-05,235,minor,2

In [18]:
apache_df.head(10)

,id,key,summary,resolution.id,resolution.description,resolution.name,priority.id,priority.name,labels,assignee,...,project.key,project.name,projectCategory.id,projectCategory.description,projectCategory.name,resolutiondate,watches.watchCount,created,updated,description
0,12451174,WW-712,Update config browser to work with the new syntax,1.0,A fix for this issue is checked into the tree ...,Fixed,4.0,Minor,[],632ec9dd,...,WW,Struts 2,10380.0,struts.apache.org,Struts Framework,2005-01-01 07:50:46,0,2005-01-01 07:47:50,2005-01-01 07:50:46,The config browser used Velocity calling the t...
1,29159,XALANC-446,XALAN_C 1.9 or current do not build on Fedora ...,1.0,A fix for this issue is checked into the tree ...,Fixed,1.0,Blocker,[],NaN,...,XALANC,XalanC,11460.0,Xalan Related Projects,Xalan,2004-12-30 05:30:36,1,2004-12-25 22:50:30,2005-01-01 10:20:52,Two types of errors:\n1- runConfigure and conf...
2,12420130,ROL-587,"Problem with ADD new post, and DELETE post.",5.0,"All attempts at reproducing this issue failed,...",Cannot Reproduce,2.0,Critical,[],4d4054ac,...,ROL,Apache Roller,10331.0,NaN,Roller,2005-01-02 15:21:00,0,2005-01-01 13:52:46,2005-01-02 15:21:00,"When trying to add new post, I was getting nex..."
3,29222,AXIS-1741,LogHandler can only work in GlobalConfiguratio...,NaN,NaN,NaN,3.0,Major,[],NaN,...,AXIS,Axis,10401.0,Axis and Axis2 related projects,Axis,NaN,0,2005-01-02 19:13:37,2005-01-02 19:35:36,org.apache.axis.handlers.LogHandler in request...
4,29233,AXIS-1745,Decoding of service is broken in org.apache.ax...,NaN,NaN,NaN,3.0,Major,[],NaN,...,AXIS,Axis,10401.0,Axis and Axis2 related projects,Axis,NaN,1,2005-01-03 03:34:52,2005-01-03 03:34:52,The following code assumes a lot of things:\n\...
5,29171,DIRNAMING-9,XmlConfigurator should support namespaces othe...,1.0,A fix for this issue is checked into the tree ...,Fixed,3.0,Major,[],b6154a7a,...,DIRNAMING,Directory Naming,10041.0,Apache Directory Project Category,Directory,2005-01-03 10:21:28,0,2004-12-27 01:34:17,2005-01-03 10:21:28,"Currently, the XmlConfigurator assumes that th..."
6,12812725,GROOVY-686,GroovyServlet will crash if parameters are pas...,1.0,A fix for this issue is checked into the tree ...,Fixed,3.0,Major,[],32a9e33f,...,GROOVY,Groovy,13860.0,Apache Groovy project,Groovy,2005-01-03 11:29:27,0,2004-12-28 18:50:52,2005-01-03 11:29:27,If parameters are being passed to a groovy ser...
7,29239,DIRNAMING-10,Port changes from tomcat-catalina,1.0,A fix for this issue is checked into the tree ...,Fixed,3.0,Major,[],b6154a7a,...,DIRNAMING,Directory Naming,10041.0,Apache Directory Project Category,Directory,2005-01-03 11:38:03,0,2005-01-03 11:16:07,2005-01-03 11:38:03,Since the [naming] sources were extracted from...
8,12812772,GROOVY-671,Groovy / Java Mismatch with simple class,1.0,A fix for this issue is checked into the tree ...,Fixed,3.0,Major,[],057c207f,...,GROOVY,Groovy,13860.0,Apache Groovy project,Groovy,2005-01-03 21:41:58,0,2004-12-02 18:18:07,2005-01-03 21:41:58,The following code compiles and runs as a java...
9,12594252,XW-259,ActionContext should always have a TextProvide...,1.0,A fix for this issue is checked into the tree ...,Fixed,4.0,Minor,[],632ec9dd,...,XW,XWork,10380.0,struts.apache.org,Struts Framework,2005-01-03 23:05:03,0,2005-01-03 14:05:55,2005-01-03 23:05:10,Right now if you access the ActionContext befo...

In [34]:
mozilla_df.columns
mozilla_df['status_category']

0       resolved
1       resolved
2       resolved
3       resolved
4       resolved
          ...
9994    resolved
9995    resolved
9996    resolved
9997    resolved
9998    resolved
Name: status_category, Length: 9999, dtype: object

In [42]:
print(mozilla_df.columns)
print(apache_df.columns)
apache_df[['resolution.id', 'resolution.description',
       'resolution.name','statusCategory.name']]

Index(['bug_id', 'creation_date', 'component_name', 'product_name',
       'short_description', 'long_description', 'assignee_name',
       'reporter_name', 'resolution_category', 'resolution_code',
       'status_category', 'status_code', 'update_date', 'quantity_of_votes',
       'quantity_of_comments', 'resolution_date', 'bug_fix_time',
       'severity_category', 'severity_code'],
      dtype='object')
Index(['id', 'key', 'summary', 'resolution.id', 'resolution.description',
       'resolution.name', 'priority.id', 'priority.name', 'labels', 'assignee',
       'status.id', 'status.description', 'status.name', 'statusCategory.id',
       'statusCategory.key', 'statusCategory.colorName', 'statusCategory.name',
       'customfield_12310921', 'creator', 'subtasks', 'reporter',
       'votes.votes', 'issuetype.id', 'issuetype.description',
       'issuetype.name', 'issuetype.subtask', 'project.id', 'project.key',
       'project.name', 'projectCategory.id', 'projectCategory.description',
       'projectCategory.name', 'resolutiondate', 'watches.watchCount',
       'created', 'updated', 'description'],
      dtype='object')

,resolution.id,resolution.description,resolution.name,statusCategory.name
0,1.0,A fix for this issue is checked into the tree ...,Fixed,Done
1,1.0,A fix for this issue is checked into the tree ...,Fixed,Done
2,5.0,"All attempts at reproducing this issue failed,...",Cannot Reproduce,Done
3,NaN,NaN,NaN,To Do
4,NaN,NaN,NaN,To Do
...,...,...,...,...
9995,1.0,A fix for this issue is checked into the tree ...,Fixed,Done
9996,3.0,The problem is a duplicate of an existing issue.,Duplicate,Done
9997,1.0,A fix for this issue is checked into the tree ...,Fixed,Done
9998,5.0,"All attempts at reproducing this issue failed,...",Cannot Reproduce,Done
9999,1.0,A fix for this issue is checked into the tree ...,Fixed,Done

In [40]:
mozilla_std = pd.DataFrame({
    'bug_id':mozilla_df['bug_id'],
    'title':mozilla_df['short_description'],
    'description':mozilla_df['long_description'],
    'severity':mozilla_df['severity_category'],
    'resolution':mozilla_df['resolution_category'],
    'status':mozilla_df['status_category'],
    'source_dataset':'Mozilla'
}
    
)

eclipse_std = pd.DataFrame({
    'bug_id':eclipse_df['bug_id'],
    'title':eclipse_df['short_description'],
    'description':eclipse_df['long_description'],
    'severity':eclipse_df ['severity_category'],
    'resolution':eclipse_df['resolution_category'],
    'status':eclipse_df['status_category'],
    'source_dataset':'Eclipse'
}
    
)

apache_std = pd.DataFrame({
    'bug_id':apache_df['key'],
    'title':apache_df['summary'],
    'description':apache_df['description'],
    'severity':apache_df ['priority.name'],
    'resolution':apache_df['resolution.name'],
    'status':apache_df['statusCategory.name'],
    'source_dataset':'Apache'
    
})

print('Mozilla:',mozilla_std.shape)
print('Eclipse:',eclipse_std.shape)
print('Apache:',apache_std.shape)

Mozilla: (9999, 7)
Eclipse: (9776, 7)
Apache: (10000, 7)

In [45]:
mozilla_std['stack_trace'] = None
eclipse_std['stack_trace'] = None
apache_std['stack_trace'] = None

mozilla_std['product_component'] = mozilla_df['product_name']
eclipse_std['product_component'] = eclipse_df['product_name']
apache_std['product_component'] = apache_df['project.name']


print(mozilla_std.shape)
print(eclipse_std.shape)
print(apache_std.shape)

mozilla_std.head()

(9999, 9)
(9776, 9)
(10000, 9)

,bug_id,title,description,severity,resolution,status,source_dataset,stack_trace,product_component
0,BUGZILLA-294734,Emergency 2.16.10 Release,2.16.9 is broken -- many users can't enter bug...,blocker,fixed,resolved,Mozilla,None,BUGZILLA
1,OTHER_APPLICATIONS-363323,DOM View is really inefficient with setting wh...,From comment in url:\n\nCurrent code:\nmenuite...,normal,fixed,resolved,Mozilla,None,OTHER_APPLICATIONS
2,SUPPORT.MOZILLA.ORG-398246,Add support for custom cookies and cache headers,Adding support for custom headers and cookie n...,blocker,fixed,resolved,Mozilla,None,SUPPORT.MOZILLA.ORG
3,RELEASE_ENGINEERING-525991,Create Major Update from 3.0.15 to 3.5.5,NaN,normal,fixed,resolved,Mozilla,None,RELEASE_ENGINEERING
4,OTHER_APPLICATIONS-318859,DCC functionality in ChatZilla isn't functional.,User-Agent: Mozilla/5.0 (Macintosh U PPC...,normal,fixed,resolved,Mozilla,None,OTHER_APPLICATIONS

In [47]:
knowledge_base_df = pd.concat([mozilla_std,eclipse_std,apache_std], ignore_index = True)
print("Comobo Size " , knowledge_base_df.shape)
knowledge_base_df['source_dataset'].value_counts()

Comobo Size  (29775, 9)

source_dataset
Apache     10000
Mozilla     9999
Eclipse     9776
Name: count, dtype: int64

In [60]:
knowledge_base_df.to_csv("C:/Users/famil/OneDrive/Desktop/AI_Smart_Bug_Analyzer_-_Fix-_Advisor-/data/knowledge_basic_combined.csv" , index = False)
print("Saved Sucessfully")

Saved Sucessfully

# TASK 7:DATA CLEANING

In [54]:
print(knowledge_base_df.isnull().sum())
print("\n\nDuplicate id : ",knowledge_base_df['bug_id'].duplicated().sum())
print("\n\nShape before cleaning : ",knowledge_base_df.shape)

bug_id                   0
title                    1
description            613
severity               354
resolution            1036
status                1036
source_dataset           0
stack_trace          29775
product_component        0
dtype: int64


Duplicate id :  0


Shape before cleaning :  (29775, 9)

In [57]:
knowledge_base_clean = knowledge_base_df.dropna(subset = ['title','description'])

knowledge_base_clean = knowledge_base_clean.fillna({
    'severity':'Unknown',
    'resolution':'Not Specificed',
    'status':'Unknown'
})

print("Shape after cleaning :",knowledge_base_clean.shape)
print("\nRemaining nulls : \n",knowledge_base_clean.isnull().sum())

Shape after cleaning : (29161, 9)

Remaining nulls :
 bug_id                   0
title                    0
description              0
severity                 0
resolution               0
status                   0
source_dataset           0
stack_trace          29161
product_component        0
dtype: int64

In [58]:
import re

def clean_text(text):
    if pd.isna(text):
        return(text)
    text =  str(text)
    text = re.sub(r'<[^>]+>',' ',text)
    text = re.sub(r'\s+',' ',text)
    return text.strip()

knowledge_base_clean['title'] = knowledge_base_clean['title'].apply(clean_text)
knowledge_base_clean['description'] = knowledge_base_clean['description'].apply(clean_text)

print('Cleaning applied . A Sample of that :')
knowledge_base_clean[['title','description']].head(3)

Cleaning applied . A Sample of that :

,title,description
0,Emergency 2.16.10 Release,2.16.9 is broken -- many users can't enter bug...
1,DOM View is really inefficient with setting wh...,From comment in url: Current code: menuitem ->...
2,Add support for custom cookies and cache headers,Adding support for custom headers and cookie n...

In [61]:
knowledge_base_clean.to_csv("C:/Users/famil/OneDrive/Desktop/AI_Smart_Bug_Analyzer_-_Fix-_Advisor-/data/knowledge_base_cleaned.csv" , index = False)
print("Saved Cleaned knowledge Base")

Saved Cleaned knowledge Base

# TASK 8:Chunking with  Langchain

In [ ]:
import sys
!{sys.executable} -m pip install langchain langchain-text-splitters

In [67]:
from langchain_text_splitters import RecursiveCharacterTextSplitter

splitter = RecursiveCharacterTextSplitter(chunk_size=500 , chunk_overlap=50)

knowledge_base_clean['full_text'] = knowledge_base_clean['title'] + ". " + knowledge_base_clean['description']

sample_text = knowledge_base_clean['full_text'].iloc[0]
chunks = splitter.split_text(sample_text)

print("Original Text Length :",len(sample_text))
print("Numberof chunks :",len(chunks))
print("\nFirst Chunk:\n",chunks[0])

Original Text Length : 173
Numberof chunks : 1

First Chunk:
 Emergency 2.16.10 Release. 2.16.9 is broken -- many users can't enter bugs on it particularly not from a fresh install. So we need to pull 2.16.9 and post a 2.16.10 instead.

In [69]:
longer_text = knowledge_base_clean['full_text'].iloc[1]
chunks = splitter.split_text(longer_text)

print("Original Text Length :",len(longer_text))
print("Numberof chunks :",len(chunks))
print("\n--- Chunk 1 ---\n",chunks[0])
print("\n--- Chunk 2 ---\n",chunks[1] if len(chunks)>1 else "(only 1 chunk)")

Original Text Length : 304
Numberof chunks : 1

--- Chunk 1 ---
 DOM View is really inefficient with setting what is to be shown. From comment in url: Current code: menuitem -> command -> toggler -> setter -> pref -> observer -> setter -> pref Proposed code: menuitem -> command -> toggler -> pref -> observer -> setter arguably we should rebuild() in the observer too.

--- Chunk 2 ---
 (only 1 chunk)

In [72]:
longest_idx = knowledge_base_clean['full_text'].str.len().idxmax()
longest_text=knowledge_base_clean['full_text'].loc[longest_idx]

print("Length of longest text:", len(longest_text))  
chunks = splitter.split_text(longest_text)

print("Length of longest text:",len(chunks))
print("Number of chunks :",len(chunks))
print("\n--- Chunk 1 ---\n",chunks[0])
print("\n--- Chunk 2 ---\n",chunks[1] if len(chunks)>1 else "(only 1 chunk)")

Length of longest text: 64610
Length of longest text: 171
Number of chunks : 171

--- Chunk 1 ---
 [FIX]I am a beginner from China, and i can't work jetspeed with db2,please help me,ok?. As followed is my db2 ddl and populate file contents. CREATE TABLE TURBINE_USER ( USER_ID INTEGER NOT NULL, LOGIN_NAME VARCHAR (32) NOT NULL, PASSWORD_VALUE VARCHAR (32) NOT NULL, FIRST_NAME VARCHAR (99) NOT NULL, LAST_NAME VARCHAR (99) NOT NULL, EMAIL VARCHAR (99), CONFIRM_VALUE VARCHAR (99), MODIFIED TIMESTAMP, CREATED TIMESTAMP, LAST_LOGIN TIMESTAMP, DISABLED VARCHAR (1), OBJECTDATA CLOB(16777215),

--- Chunk 2 ---
 DISABLED VARCHAR (1), OBJECTDATA CLOB(16777215), PASSWORD_CHANGED TIMESTAMP, UNIQUE (LOGIN_NAME) ); ALTER TABLE TURBINE_USER ADD PRIMARY KEY (USER_ID); CREATE TABLE TURBINE_ROLE ( ROLE_ID INTEGER NOT NULL, ROLE_NAME VARCHAR (99) NOT NULL, OBJECTDATA CLOB(16777215), UNIQUE (ROLE_NAME) ); ALTER TABLE TURBINE_ROLE ADD PRIMARY KEY (ROLE_ID); CREATE TABLE TURBINE_GROUP ( GROUP_ID INTEGER NOT NULL, GROUP_NAME VARCHAR (99) NOT NULL, OBJECTDATA CLOB(16777215), UNIQUE (GROUP_NAME) ); ALTER TABLE

In [73]:
# Cap any single text at 3000 characters before chunking (keeps outliers from exploding chunk count)
knowledge_base_clean['full_text'] = knowledge_base_clean['full_text'].str[:3000]

In [75]:
all_chunks = []

for idx , row  in knowledge_base_clean.iterrows():
    text_chunks = splitter.split_text(row['full_text'])
    for i , chunk in enumerate(text_chunks):
        all_chunks.append({
            'chunk_id':f"{row['bug_id']}_chunk{i}",
            'bug_id':row['bug_id'],
            'chunk_text':chunk,
            'title':row['title'],
            'severity':row['severity'],
            'resolution':row['resolution'],
            'status':row['status'],
            'source_dataset':row['source_dataset']
        })

chunks_df = pd.DataFrame(all_chunks)
print("Total chunks created:",chunks_df.shape[0])
print("From original rows:", knowledge_base_clean.shape[0])
chunks_df.head(55)

Total chunks created: 56862
From original rows: 29161

,chunk_id,bug_id,chunk_text,title,severity,resolution,status,source_dataset
0,BUGZILLA-294734_chunk0,BUGZILLA-294734,Emergency 2.16.10 Release. 2.16.9 is broken --...,Emergency 2.16.10 Release,blocker,fixed,resolved,Mozilla
1,OTHER_APPLICATIONS-363323_chunk0,OTHER_APPLICATIONS-363323,DOM View is really inefficient with setting wh...,DOM View is really inefficient with setting wh...,normal,fixed,resolved,Mozilla
2,SUPPORT.MOZILLA.ORG-398246_chunk0,SUPPORT.MOZILLA.ORG-398246,Add support for custom cookies and cache heade...,Add support for custom cookies and cache headers,blocker,fixed,resolved,Mozilla
3,SUPPORT.MOZILLA.ORG-398246_chunk1,SUPPORT.MOZILLA.ORG-398246,at re-implementing some session libs I have fr...,Add support for custom cookies and cache headers,blocker,fixed,resolved,Mozilla
4,OTHER_APPLICATIONS-318859_chunk0,OTHER_APPLICATIONS-318859,DCC functionality in ChatZilla isn't functiona...,DCC functionality in ChatZilla isn't functional.,normal,fixed,resolved,Mozilla
5,OTHER_APPLICATIONS-318859_chunk1,OTHER_APPLICATIONS-318859,DCC offers matched. [18:54:22] [INFO] You must...,DCC functionality in ChatZilla isn't functional.,normal,fixed,resolved,Mozilla
6,OTHER_APPLICATIONS-318859_chunk2,OTHER_APPLICATIONS-318859,(67.186.207.96:55938) [Cancel]. [19:05:06][DCC...,DCC functionality in ChatZilla isn't functional.,normal,fixed,resolved,Mozilla
7,OTHER_APPLICATIONS-318859_chunk3,OTHER_APPLICATIONS-318859,function. Actual Results: Note that the functi...,DCC functionality in ChatZilla isn't functional.,normal,fixed,resolved,Mozilla
8,DEVELOPER.MOZILLA.ORG-416840_chunk0,DEVELOPER.MOZILLA.ORG-416840,Fix and cruft. Since we removed the breadcrumb...,Fix and cruft,normal,fixed,resolved,Mozilla
9,MARKETPLACE_GRAVEYARD-977729_chunk0,MARKETPLACE_GRAVEYARD-977729,add a waffle to disable the theme queue. This ...,add a waffle to disable the theme queue,normal,fixed,resolved,Mozilla
10,THUNDERBIRD-339875_chunk0,THUNDERBIRD-339875,ship ga-IE for 1.5.0.5. the ga-IE locale for T...,ship ga-IE for 1.5.0.5,normal,fixed,resolved,Mozilla
11,FIREFOX-420556_chunk0,FIREFOX-420556,sidebarheader on GNOME has a transparent backg...,sidebarheader on GNOME has a transparent backg...,normal,fixed,resolved,Mozilla
12,FIREFOX-420556_chunk1,FIREFOX-420556,top and bottom borders and it's unclear why th...,sidebarheader on GNOME has a transparent backg...,normal,fixed,resolved,Mozilla
13,FIREFOX-420556_chunk2,FIREFOX-420556,border rules to be applied and I looked at thr...,sidebarheader on GNOME has a transparent backg...,normal,fixed,resolved,Mozilla
14,FIREFOX-420556_chunk3,FIREFOX-420556,top and bottom border rules. Here's a patch th...,sidebarheader on GNOME has a transparent backg...,normal,fixed,resolved,Mozilla
15,FIREFOX-420556_chunk4,FIREFOX-420556,in the sidebar itself (f.e. the Search label i...,sidebarheader on GNOME has a transparent backg...,normal,fixed,resolved,Mozilla
16,MOZILLA_LOCALIZATIONS-415621_chunk0,MOZILLA_LOCALIZATIONS-415621,Firefox 3 mk release tracker. This is a tracke...,Firefox 3 mk release tracker,normal,fixed,resolved,Mozilla
17,CORE-254510_chunk0,CORE-254510,Bug 200433 regressed by patch in bug 253597. T...,Bug 200433 regressed by patch in bug 253597,major,fixed,resolved,Mozilla
18,CORE-204573_chunk0,CORE-204573,View-source highlighting is incorrect for XML ...,View-source highlighting is incorrect for XML ...,normal,fixed,resolved,Mozilla
19,CORE-204573_chunk1,CORE-204573,in a tag name (e. g. the attached file). Actua...,View-source highlighting is incorrect for XML ...,normal,fixed,resolved,Mozilla
20,CORE-204573_chunk2,CORE-204573,and Mozilla 1.0 (PC/Linux) - In the case of an...,View-source highlighting is incorrect for XML ...,normal,fixed,resolved,Mozilla
21,THUNDERBIRD-412434_chunk0,THUNDERBIRD-412434,opening a window with -chrome does not work an...,opening a window with -chrome does not work an...,normal,fixed,resolved,Mozilla
22,THUNDERBIRD-412434_chunk1,THUNDERBIRD-412434,but that function is defined nowhere in the fi...,opening a window with -chrome does not work an...,normal,fixed,resolved,Mozilla
23,OTHER_APPLICATIONS_GRAVEYARD-391445_chunk0,OTHER_APPLICATIONS_GRAVEYARD-391445,Unsightly border around clicked tabs. With the...,Unsightly border around clicked tabs,normal,fixed,resolved,Mozilla
24,FIREFOX_OS_GRAVEYARD-942470_chunk0,FIREFOX_OS_GRAVEYARD-942470,test_user_agent_updates.htmltest_user_agent_ov...,test_user_agent_updates.htmltest_user_agent_ov...,normal,fixed,resolved,Mozilla
25,FIREFOX_OS_GRAVEYARD-942470_chunk1,FIREFOX_OS_GRAVEYARD-942470,OS X 10.8) != -1 but intermittently instead of...,test_user_agent_updates.htmltest_user_agent_ov...,normal,fixed,resolved,Mozilla
26,TECH_EVANGELISM_GRAVEYARD-142958_chunk0,TECH_EVANGELISM_GRAVEYARD-142958,oracle.usu.ru - form is submitted incorrectly ...,oracle.usu.ru - form is submitted incorrectly ...,normal,fixed,resolved,Mozilla
27,TECH_EVANGELISM_GRAVEYARD-142958_chunk1,TECH_EVANGELISM_GRAVEYARD-142958,is only one text field (for entering the searc...,oracle.usu.ru - form is submitted incorrectly ...,normal,fixed,resolved,Mozilla
28,TECH_EVANGELISM_GRAVEYARD-142958_chunk2,TECH_EVANGELISM_GRAVEYARD-142958,it should looks like: 'XXX mathes found. Your ...,oracle.usu.ru - form is submitted incorrectly ...,normal,fixed,resolved,Mozilla
29,TECH_EVANGELISM_GRAVEYARD-142958_chunk3,TECH_EVANGELISM_GRAVEYARD-142958,has an OnClick event document.forms[0].submit(...,oracle.usu.ru - form is submitted incorrectly ...,normal,fixed,resolved,Mozilla
30,CORE-128371_chunk0,CORE-128371,menu items on the left side are not displayed....,menu items on the left side are not displayed,major,fixed,resolved,Mozilla
31,SEAMONKEY-160672_chunk0,SEAMONKEY-160672,[FIX]XP filepicker's modeGetFolder looks too m...,[FIX]XP filepicker's modeGetFolder looks too m...,normal,fixed,resolved,Mozilla
32,MOZILLA.ORG_GRAVEYARD-471000_chunk0,MOZILLA.ORG_GRAVEYARD-471000,qm-plinux-trunk04 needs a kick.. Currently unr...,qm-plinux-trunk04 needs a kick.,normal,fixed,resolved,Mozilla
33,CORE-459938_chunk0,CORE-459938,Video has incorrect colours. The video in the ...,Video has incorrect colours,normal,fixed,resolved,Mozilla
34,SEAMONKEY-57480_chunk0,SEAMONKEY-57480,problem with getting back to Font size 100% af...,problem with getting back to Font size 100% af...,normal,fixed,resolved,Mozilla
35,BUGZILLA-58242_chunk0,BUGZILLA-58242,relogin.cgi fails to delete server's copy of t...,relogin.cgi fails to delete server's copy of t...,minor,fixed,resolved,Mozilla
36,BUGZILLA-58242_chunk1,BUGZILLA-58242,SendSQL(delete from logincookies where userid=...,relogin.cgi fails to delete server's copy of t...,minor,fixed,resolved,Mozilla
37,FIREFOX_BUILD_SYSTEM-454709_chunk0,FIREFOX_BUILD_SYSTEM-454709,WinCE Resource Compiling Needs Shunt Applicati...,WinCE Resource Compiling Needs Shunt Application,normal,fixed,resolved,Mozilla
38,OTHER_APPLICATIONS-315913_chunk0,OTHER_APPLICATIONS-315913,Replace RDF userlist with direct nsITreeView i...,Replace RDF userlist with direct nsITreeView i...,normal,fixed,resolved,Mozilla
39,OTHER_APPLICATIONS-315913_chunk1,OTHER_APPLICATIONS-315913,proposal is changing the tree from a content v...,Replace RDF userlist with direct nsITreeView i...,normal,fixed,resolved,Mozilla
40,OTHER_APPLICATIONS-315913_chunk2,OTHER_APPLICATIONS-315913,are therefore removed in setCurrentObject my_c...,Replace RDF userlist with direct nsITreeView i...,normal,fixed,resolved,Mozilla
41,OTHER_APPLICATIONS-315913_chunk3,OTHER_APPLICATIONS-315913,row as the builder view does not permit arbitr...,Replace RDF userlist with direct nsITreeView i...,normal,fixed,resolved,Mozilla
42,MOZILLA.ORG_GRAVEYARD-516424_chunk0,MOZILLA.ORG_GRAVEYARD-516424,MDC badly broken this morning. MDC appears to ...,MDC badly broken this morning,blocker,fixed,resolved,Mozilla
43,MOZILLA_LOCALIZATIONS-372935_chunk0,MOZILLA_LOCALIZATIONS-372935,[ro] migration wizard string change. We want t...,[ro] migration wizard string change,normal,fixed,resolved,Mozilla
44,MOZILLA_LOCALIZATIONS-372935_chunk1,MOZILLA_LOCALIZATIONS-372935,The corresponding patch is the en-US part in h...,[ro] migration wizard string change,normal,fixed,resolved,Mozilla
45,TECH_EVANGELISM_GRAVEYARD-79139_chunk0,TECH_EVANGELISM_GRAVEYARD-79139,Danawa Korea Strict mode page has extraneous -...,Danawa Korea Strict mode page has extraneous -...,normal,fixed,resolved,Mozilla
46,CORE-353334_chunk0,CORE-353334,[FIX]Permission denied error scripting SVG fro...,[FIX]Permission denied error scripting SVG fro...,normal,fixed,resolved,Mozilla
47,CORE-353334_chunk1,CORE-353334,URL-encoded SVG document. I then add the objec...,[FIX]Permission denied error scripting SVG fro...,normal,fixed,resolved,Mozilla
48,CORE-353334_chunk2,CORE-353334,I have yet to see the same error when the file...,[FIX]Permission denied error scripting SVG fro...,normal,fixed,resolved,Mozilla
49,MOZILLA.ORG-83075_chunk0,MOZILLA.ORG-83075,Quip List requested. Is there any list of curr...,Quip List requested,normal,fixed,resolved,Mozilla
50,CAMINO_GRAVEYARD-294848_chunk0,CAMINO_GRAVEYARD-294848,Can't override dialog warning of duplicate ssl...,Can't override dialog warning of duplicate ssl...,normal,fixed,resolved,Mozilla
51,CAMINO_GRAVEYARD-294848_chunk1,CAMINO_GRAVEYARD-294848,for all their routers. Camino gives an error w...,Can't override dialog warning of duplicate ssl...,normal,fixed,resolved,Mozilla
52,CAMINO_GRAVEYARD-294848_chunk2,CAMINO_GRAVEYARD-294848,use a different browser. Firefox gives a simil...,Can't override dialog warning of duplicate ssl...,normal,fixed,resolved,Mozilla
53,CAMINO_GRAVEYARD-294848_chunk3,CAMINO_GRAVEYARD-294848,the router. Expected Results: Allow the user t...,Can't override dialog warning of duplicate ssl...,normal,fixed,resolved,Mozilla
54,INFRASTRUCTURE_&_OPERATIONS-848951_chunk0,INFRASTRUCTURE_&_OPERATIONS-848951,remove network block for the following hosts i...,remove network block for the following hosts i...,normal,fixed,resolved,Mozilla

In [76]:
chunks_df.to_csv("C:/Users/famil/OneDrive/Desktop/AI_Smart_Bug_Analyzer_-_Fix-_Advisor-/data/chunks_df.csv",index=False)
print("Saved Chunks")

Saved Chunks

# Task 9:Embedding

In [3]:
#!pip install pandas
import pandas as pd

# Reload your progress instead of redoing Tasks 6-8
knowledge_base_clean = pd.read_csv("C:/Users/famil/OneDrive/Desktop/AI_Smart_Bug_Analyzer_-_Fix-_Advisor-/data/knowledge_base_cleaned.csv")
chunks_df = pd.read_csv("C:/Users/famil/OneDrive/Desktop/AI_Smart_Bug_Analyzer_-_Fix-_Advisor-/data/chunks_df.csv")

print("Knowledge base reloaded:", knowledge_base_clean.shape)
print("Chunks reloaded:", chunks_df.shape)

Knowledge base reloaded: (29161, 9)
Chunks reloaded: (56862, 8)

In [2]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer('all-MiniLM-L6-v2')

print("Model loaded successfully")
print("Embedding dimension:", model.get_sentence_embedding_dimension())

[transformers] Disabling PyTorch because PyTorch >= 2.4 is required but found 2.2.2+cpu
[transformers] PyTorch was not found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
[transformers] PyTorch was not found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.

NameError: name 'nn' is not defined

In [ ]:
import sys
!{sys.executable} -m pip install sentence-transformers

In [ ]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer('all-MiniLM-L6-v2')

print("Model loaded succesfully")
print("Embedding dimension:",model.get_sentence_embedding_dimension())

In [3]:
import torch
print("Torch version:", torch.__version__)
print("Torch loaded fine, testing nn module...")
x = torch.nn.Linear(10, 5)
print("torch.nn works fine")

Torch version: 2.2.2+cpu
Torch loaded fine, testing nn module...
torch.nn works fine

In [ ]:
import sys
!{sys.executable} -m pip install --upgrade sentence-transformers transformers

In [ ]:
import sys
!{sys.executable} -m pip uninstall torch -y
!{sys.executable} -m pip install torch==2.2.2 --index-url https://download.pytorch.org/whl/cpu

In [ ]:
!{sys.executable} -m pip install torch --index-url https://download.pytorch.org/whl/cpu

In [ ]:
import sys
!{sys.executable} -m pip install "sentence-transformers==2.7.0" "transformers==4.39.3" --force-reinstall

In [ ]:
import sys
!{sys.executable} -m pip install --upgrade --force-reinstall numpy pandas

In [ ]:
import pandas as pd

knowledge_base_clean = pd.read_csv("../data/knowledge_base_cleaned.csv")
chunks_df = pd.read_csv("../data/chunks.csv")

print("Knowledge base reloaded:", knowledge_base_clean.shape)
print("Chunks reloaded:", chunks_df.shape)

In [17]:
import pandas

ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

In [5]:
import sys
print(sys.executable)

C:\Users\famil\anaconda3\python.exe

In [6]:
import numpy
print(numpy.__version__)

2.4.6

In [ ]:
pip show numpy

In [ ]:
pip show pandas

In [19]:
import numpy
print(numpy.__version__)

2.4.6

In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=384, stop_words='english')

embeddings = vectorizer.fit_transform(chunks_df['chunk_text'])

print("Embeddings shape:", embeddings.shape)

Embeddings shape: (56862, 384)

# Task 10: Vector Database (ChromaDB)

In [ ]:
import sys
!{sys.executable} -m pip install chromadb

In [7]:
import chromadb

client = chromadb.Client()
collection = client.create_collection(name="bug_knowledge_base")

# Convert TF-IDF sparse matrix to lists for ChromaDB
embeddings_list = embeddings.toarray().tolist()

# Add in batches (ChromaDB works better with reasonable batch sizes)
batch_size = 5000
for i in range(0, len(chunks_df), batch_size):
    batch_end = min(i + batch_size, len(chunks_df))
    collection.add(
        ids=chunks_df['chunk_id'].iloc[i:batch_end].tolist(),
        embeddings=embeddings_list[i:batch_end],
        documents=chunks_df['chunk_text'].iloc[i:batch_end].tolist(),
        metadatas=chunks_df[['bug_id', 'title', 'severity', 'resolution', 'status', 'source_dataset']].iloc[i:batch_end].to_dict('records')
    )
    print(f"Added batch {i} to {batch_end}")

print("Total items in collection:", collection.count())

Added batch 0 to 5000
Added batch 5000 to 10000
Added batch 10000 to 15000
Added batch 15000 to 20000
Added batch 20000 to 25000
Added batch 25000 to 30000
Added batch 30000 to 35000
Added batch 35000 to 40000
Added batch 40000 to 45000
Added batch 45000 to 50000
Added batch 50000 to 55000
Added batch 55000 to 56862
Total items in collection: 56862

In [9]:
client.delete_collection(name="bug_knowledge_base")  # remove the broken one

collection = client.create_collection(
    name="bug_knowledge_base",
    metadata={"hnsw:space": "cosine"}
)

In [10]:
# Convert TF-IDF sparse matrix to lists for ChromaDB
embeddings_list = embeddings.toarray().tolist()

# Add in batches
batch_size = 5000
for i in range(0, len(chunks_df), batch_size):
    batch_end = min(i + batch_size, len(chunks_df))
    collection.add(
        ids=chunks_df['chunk_id'].iloc[i:batch_end].tolist(),
        embeddings=embeddings_list[i:batch_end],
        documents=chunks_df['chunk_text'].iloc[i:batch_end].tolist(),
        metadatas=chunks_df[['bug_id', 'title', 'severity', 'resolution', 'status', 'source_dataset']].iloc[i:batch_end].to_dict('records')
    )
    print(f"Added batch {i} to {batch_end}")

print("Total items in collection:", collection.count())

Added batch 0 to 5000
Added batch 5000 to 10000
Added batch 10000 to 15000
Added batch 15000 to 20000
Added batch 20000 to 25000
Added batch 25000 to 30000
Added batch 30000 to 35000
Added batch 35000 to 40000
Added batch 40000 to 45000
Added batch 45000 to 50000
Added batch 50000 to 55000
Added batch 55000 to 56862
Total items in collection: 56862

In [13]:
import numpy as np

print("Non-zero values in query vector:", np.count_nonzero(query_vector))
print("Query vector shape:", np.array(query_vector).shape)

# Which of our query words actually made it into the vocabulary?
vocab = vectorizer.vocabulary_
for word in ["application", "crashes", "crash", "login", "special", "characters", "character", "password"]:
    print(word, "->", "IN VOCAB" if word in vocab else "NOT in vocab")

Non-zero values in query vector: 1
Query vector shape: (1, 384)
application -> IN VOCAB
crashes -> NOT in vocab
crash -> IN VOCAB
login -> NOT in vocab
special -> NOT in vocab
characters -> NOT in vocab
character -> NOT in vocab
password -> NOT in vocab

In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=3000, stop_words='english')
embeddings = vectorizer.fit_transform(chunks_df['chunk_text'])

print("Embeddings shape:", embeddings.shape)

Embeddings shape: (56862, 3000)

In [15]:
client.delete_collection(name="bug_knowledge_base")
collection = client.create_collection(
    name="bug_knowledge_base",
    metadata={"hnsw:space": "cosine"}
)

embeddings_list = embeddings.toarray().tolist()

batch_size = 5000
for i in range(0, len(chunks_df), batch_size):
    batch_end = min(i + batch_size, len(chunks_df))
    collection.add(
        ids=chunks_df['chunk_id'].iloc[i:batch_end].tolist(),
        embeddings=embeddings_list[i:batch_end],
        documents=chunks_df['chunk_text'].iloc[i:batch_end].tolist(),
        metadatas=chunks_df[['bug_id', 'title', 'severity', 'resolution', 'status', 'source_dataset']].iloc[i:batch_end].to_dict('records')
    )
    print(f"Added batch {i} to {batch_end}")

print("Total items in collection:", collection.count())

Added batch 0 to 5000
Added batch 5000 to 10000
Added batch 10000 to 15000
Added batch 15000 to 20000
Added batch 20000 to 25000
Added batch 25000 to 30000
Added batch 30000 to 35000
Added batch 35000 to 40000
Added batch 40000 to 45000
Added batch 45000 to 50000
Added batch 50000 to 55000
Added batch 55000 to 56862
Total items in collection: 56862

In [7]:
embeddings_list = embeddings.toarray().tolist()
print("Done converting to list.")

Done converting to list.

In [7]:
embeddings_list = embeddings.toarray().tolist()
print("Done converting to list.")

Done converting to list.

In [4]:
import chromadb
print(chromadb.__version__)

1.1.1

In [5]:
import pandas as pd

chunks_df = pd.read_csv("../data/chunks_df.csv")
print(chunks_df.shape)

(56862, 8)

In [6]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=3000, stop_words='english')
embeddings = vectorizer.fit_transform(chunks_df['chunk_text'])

print("Embeddings shape:", embeddings.shape)

Embeddings shape: (56862, 3000)

In [7]:
embeddings_list = embeddings.toarray().tolist()
print("Done converting to list.")

Done converting to list.

In [2]:
# persistent_collection = persistent_client.create_collection(
#     name="bug_knowledge_base",
#     metadata={"hnsw:space": "cosine"}
# )


persistent_client = chromadb.PersistentClient(path="C:/temp/chroma_db")

persistent_collection = persistent_client.create_collection(
    name="bug_knowledge_base",
    metadata={"hnsw:space": "cosine"}
)

batch_size = 5000
for i in range(0, len(chunks_df), batch_size):
    batch_end = min(i + batch_size, len(chunks_df))
    persistent_collection.add(
        ids=chunks_df['chunk_id'].iloc[i:batch_end].tolist(),
        embeddings=embeddings_list[i:batch_end],
        documents=chunks_df['chunk_text'].iloc[i:batch_end].tolist(),
        metadatas=chunks_df[['bug_id', 'title', 'severity', 'resolution', 'status', 'source_dataset']].iloc[i:batch_end].to_dict('records')
    )
    print(f"Added batch {i} to {batch_end}")

print("Total items in persistent collection:", persistent_collection.count())

NameError: name 'chromadb' is not defined

In [2]:
# persistent_collection = persistent_client.create_collection(
#     name="bug_knowledge_base",
#     metadata={"hnsw:space": "cosine"}
# )


persistent_client = chromadb.PersistentClient(path="C:/temp/chroma_db")

persistent_collection = persistent_client.create_collection(
    name="bug_knowledge_base",
    metadata={"hnsw:space": "cosine"}
)

batch_size = 5000
for i in range(0, len(chunks_df), batch_size):
    batch_end = min(i + batch_size, len(chunks_df))
    persistent_collection.add(
        ids=chunks_df['chunk_id'].iloc[i:batch_end].tolist(),
        embeddings=embeddings_list[i:batch_end],
        documents=chunks_df['chunk_text'].iloc[i:batch_end].tolist(),
        metadatas=chunks_df[['bug_id', 'title', 'severity', 'resolution', 'status', 'source_dataset']].iloc[i:batch_end].to_dict('records')
    )
    print(f"Added batch {i} to {batch_end}")

print("Total items in persistent collection:", persistent_collection.count())

NameError: name 'chromadb' is not defined

In [3]:
persistent_client.delete_collection(name="bug_knowledge_base")
print("Deleted old collection.")

Deleted old collection.

In [9]:
existing = persistent_client.list_collections()
print(existing)

[Collection(name=bug_knowledge_base)]

In [1]:
existing_collection = persistent_client.get_collection(name="bug_knowledge_base")
print("Count:", existing_collection.count())

NameError: name 'persistent_client' is not defined

In [14]:
persistent_collection = existing_collection

batch_size = 5000
for i in range(0, len(chunks_df), batch_size):
    batch_end = min(i + batch_size, len(chunks_df))
    persistent_collection.add(
        ids=chunks_df['chunk_id'].iloc[i:batch_end].tolist(),
        embeddings=embeddings_list[i:batch_end],
        documents=chunks_df['chunk_text'].iloc[i:batch_end].tolist(),
        metadatas=chunks_df[['bug_id', 'title', 'severity', 'resolution', 'status', 'source_dataset']].iloc[i:batch_end].to_dict('records')
    )
    print(f"Added batch {i} to {batch_end}")

print("Total items in persistent collection:", persistent_collection.count())

Added batch 0 to 5000
Added batch 5000 to 10000
Added batch 10000 to 15000
Added batch 15000 to 20000
Added batch 20000 to 25000
Added batch 25000 to 30000
Added batch 30000 to 35000
Added batch 35000 to 40000
Added batch 40000 to 45000
Added batch 45000 to 50000
Added batch 50000 to 55000
Added batch 55000 to 56862
Total items in persistent collection: 56862

In [16]:
import sklearn
print(sklearn.__version__)

1.4.0

In [1]:
1+2

3

In [9]:
import numpy as np

# Save the embeddings matrix
np.save("../src/embeddings.npy", embeddings.toarray())

# Save the metadata needed to display results (aligned by row index with embeddings)
chunks_df[['bug_id', 'title', 'severity', 'resolution', 'status', 'source_dataset']].to_csv("../src/chunks_metadata.csv", index=False)

print("Saved embeddings and metadata.")

Saved embeddings and metadata.

In [1]:
import pandas as pd
chunks_df = pd.read_csv("../data/chunks_df.csv")
print(chunks_df.shape)

(56862, 8)

In [2]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer('all-MiniLM-L6-v2')
print("Model loaded")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Model loaded

In [ ]:
chunk_texts = chunks_df['chunk_text'].tolist()

embeddings = model.encode(
    chunk_texts,
    batch_size=64,
    show_progress_bar=True,
    convert_to_numpy=True
)

print("Embeddings shape:", embeddings.shape)

In [4]:
import time

start = time.time()
test_embeddings = model.encode(chunk_texts[:5], convert_to_numpy=True)
print("Took", time.time() - start, "seconds")
print(test_embeddings.shape)

Took 0.47360730171203613 seconds
(5, 384)

In [5]:
import time

start = time.time()
test_embeddings_1000 = model.encode(
    chunk_texts[:1000],
    batch_size=64,
    convert_to_numpy=True
)
print("Took", time.time() - start, "seconds")
print(test_embeddings_1000.shape)

Took 43.57127594947815 seconds
(1000, 384)

In [6]:
import numpy as np
import time

all_embeddings = []
chunk_size = 10000
total = len(chunk_texts)

for i in range(0, total, chunk_size):
    batch_texts = chunk_texts[i:i+chunk_size]
    start = time.time()
    batch_embeddings = model.encode(batch_texts, batch_size=64, convert_to_numpy=True)
    all_embeddings.append(batch_embeddings)
    print(f"Processed {i} to {min(i+chunk_size, total)} — took {time.time()-start:.1f}s")

embeddings = np.vstack(all_embeddings)
print("Final embeddings shape:", embeddings.shape)

Processed 0 to 10000 — took 487.7s
Processed 10000 to 20000 — took 472.8s
Processed 20000 to 30000 — took 457.5s
Processed 30000 to 40000 — took 504.3s
Processed 40000 to 50000 — took 457.9s
Processed 50000 to 56862 — took 315.1s
Final embeddings shape: (56862, 384)

In [8]:
import numpy as np

np.save("../src/embeddings_real.npy", embeddings)
print("Saved real embeddings:", embeddings.shape)

Saved real embeddings: (56862, 384)

In [9]:
print(chunks_df['source_dataset'].value_counts())

source_dataset
Apache     20443
Eclipse    19025
Mozilla    17394
Name: count, dtype: int64

# Task 11

In [16]:
query_text = "application crashes on login with special characters in password"
query_vector = vectorizer.transform([query_text]).toarray().tolist()

results = collection.query(
    query_embeddings=query_vector,
    n_results=5
)

for i in range(len(results['ids'][0])):
    print(f"Match {i+1}: {results['metadatas'][0][i]['title']}")
    print(f"  Severity: {results['metadatas'][0][i]['severity']} | Source: {results['metadatas'][0][i]['source_dataset']}")
    print()

Match 1: Special characters don't show up on config page
  Severity: normal | Source: Mozilla

Match 2: Java applet password field gains focus but cannot be typed in.
  Severity: major | Source: Mozilla

Match 3: Login Fails if token is reset while waiting for a password.
  Severity: normal | Source: Mozilla

Match 4: [pwd-mngr] Password incorrectly stored
  Severity: minor | Source: Mozilla

Match 5: [pwd-mngr] Password incorrectly stored
  Severity: minor | Source: Mozilla

In [15]:
query_text = "application crashes on login with special characters in password"
query_vector = vectorizer.transform([query_text]).toarray().tolist()
results = persistent_collection.query(
    query_embeddings=query_vector,
    n_results=5
)
for i in range(len(results['ids'][0])):
    print(f"Match {i+1}: {results['metadatas'][0][i]['title']}")
    print(f"  Severity: {results['metadatas'][0][i]['severity']} | Source: {results['metadatas'][0][i]['source_dataset']}")
    print()

Match 1: Special characters don't show up on config page
  Severity: normal | Source: Mozilla

Match 2: Java applet password field gains focus but cannot be typed in.
  Severity: major | Source: Mozilla

Match 3: Login Fails if token is reset while waiting for a password.
  Severity: normal | Source: Mozilla

Match 4: [pwd-mngr] Password incorrectly stored
  Severity: minor | Source: Mozilla

Match 5: [pwd-mngr] Password incorrectly stored
  Severity: minor | Source: Mozilla

In [11]:
from sklearn.metrics.pairwise import cosine_similarity

In [13]:
test_queries = [
    "application crashes on login with special characters in password",
    "build fails with dependency resolution error",
    "editor freezes when opening large file",
    "null pointer exception on startup",
    "plugin fails to load after update",
    "server returns 500 error on deployment",
    "memory leak during long running session",
    "syntax highlighting broken in code editor",
    "authentication token expires too quickly",
    "unable to connect to database after timeout"
]

for q in test_queries:
    qvec = model.encode([q], convert_to_numpy=True)
    sims = cosine_similarity(qvec, embeddings)[0]
    best_idx = sims.argmax()
    row = chunks_df.iloc[best_idx]
    print(f"Query: {q}")
    print(f"  Best match: {row['title']}  |  Source: {row['source_dataset']}  |  Score: {sims[best_idx]:.3f}")
    print()

Query: application crashes on login with special characters in password
  Best match: password manager files have Unix line endings on Windows  |  Source: Mozilla  |  Score: 0.582

Query: build fails with dependency resolution error
  Best match: AIX Compilation error for 3.7a1pre source js/src/jsvector.h line 677.21: 1540-0274 (S) The name lookup for PointerRangeSize did not find a declaration  |  Source: Mozilla  |  Score: 0.735

Query: editor freezes when opening large file
  Best match: Opening large files to compare freezes the UI thread.  |  Source: Eclipse  |  Score: 0.709

Query: null pointer exception on startup
  Best match: engineConfigFactoryMissing (for concurrent requests)  |  Source: Apache  |  Score: 0.631

Query: plugin fails to load after update
  Best match: Update must uninstall the bundle from the osgi layer before deleting the file from the disk  |  Source: Eclipse  |  Score: 0.526

Query: server returns 500 error on deployment
  Best match: WSDL faults not being deserialised  |  Source: Apache  |  Score: 0.506

Query: memory leak during long running session
  Best match: OutOfMemoryError when creating more than one report. Increasing max heap size does only help temporarily.  |  Source: Eclipse  |  Score: 0.701

Query: syntax highlighting broken in code editor
  Best match: Java editor syntax highlighting problems  |  Source: Eclipse  |  Score: 0.697

Query: authentication token expires too quickly
  Best match: Cookie expiration date is limited to 01/18/2038 10:14:07 PM  |  Source: Mozilla  |  Score: 0.507

Query: unable to connect to database after timeout
  Best match: Error connection Time out, when expired session in DB (Oracle 8.1.7.4)  |  Source: Apache  |  Score: 0.631

# save file in pickle and other tests

In [17]:
import pickle

with open("vectorizer.pkl", "wb") as f:
    pickle.dump(vectorizer, f)

print("Vectorizer saved.")

Vectorizer saved.

In [18]:
import os
print("Current working directory:", os.getcwd())
print("File exists:", os.path.exists("vectorizer.pkl"))
print("File size (KB):", os.path.getsize("vectorizer.pkl") / 1024)

Current working directory: C:\Users\famil\OneDrive\Desktop\AI_Smart_Bug_Analyzer_-_Fix-_Advisor-\notebooks
File exists: True
File size (KB): 107.6220703125

In [19]:
with open("../src/vectorizer.pkl", "wb") as f:
    pickle.dump(vectorizer, f)

print("Saved to src/ as well.")

Saved to src/ as well.

In [20]:
import os
print("Exists in src/:", os.path.exists("../src/vectorizer.pkl"))

Exists in src/: True

In [4]:
import chromadb
print(chromadb.__version__)

1.1.1

In [5]:
import pandas as pd

chunks_df = pd.read_csv("../data/chunks_df.csv")
print(chunks_df.shape)

(56862, 8)

In [6]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=3000, stop_words='english')
embeddings = vectorizer.fit_transform(chunks_df['chunk_text'])

print("Embeddings shape:", embeddings.shape)

Embeddings shape: (56862, 3000)

In [7]:
embeddings_list = embeddings.toarray().tolist()
print("Done converting to list.")

Done converting to list.

In [3]:
persistent_client.delete_collection(name="bug_knowledge_base")
print("Deleted old collection.")

Deleted old collection.

In [9]:
existing = persistent_client.list_collections()
print(existing)

[Collection(name=bug_knowledge_base)]

In [1]:
existing_collection = persistent_client.get_collection(name="bug_knowledge_base")
print("Count:", existing_collection.count())

NameError: name 'persistent_client' is not defined

In [14]:
persistent_collection = existing_collection

batch_size = 5000
for i in range(0, len(chunks_df), batch_size):
    batch_end = min(i + batch_size, len(chunks_df))
    persistent_collection.add(
        ids=chunks_df['chunk_id'].iloc[i:batch_end].tolist(),
        embeddings=embeddings_list[i:batch_end],
        documents=chunks_df['chunk_text'].iloc[i:batch_end].tolist(),
        metadatas=chunks_df[['bug_id', 'title', 'severity', 'resolution', 'status', 'source_dataset']].iloc[i:batch_end].to_dict('records')
    )
    print(f"Added batch {i} to {batch_end}")

print("Total items in persistent collection:", persistent_collection.count())

Added batch 0 to 5000
Added batch 5000 to 10000
Added batch 10000 to 15000
Added batch 15000 to 20000
Added batch 20000 to 25000
Added batch 25000 to 30000
Added batch 30000 to 35000
Added batch 35000 to 40000
Added batch 40000 to 45000
Added batch 45000 to 50000
Added batch 50000 to 55000
Added batch 55000 to 56862
Total items in persistent collection: 56862

In [15]:
query_text = "application crashes on login with special characters in password"
query_vector = vectorizer.transform([query_text]).toarray().tolist()
results = persistent_collection.query(
    query_embeddings=query_vector,
    n_results=5
)
for i in range(len(results['ids'][0])):
    print(f"Match {i+1}: {results['metadatas'][0][i]['title']}")
    print(f"  Severity: {results['metadatas'][0][i]['severity']} | Source: {results['metadatas'][0][i]['source_dataset']}")
    print()

Match 1: Special characters don't show up on config page
  Severity: normal | Source: Mozilla

Match 2: Java applet password field gains focus but cannot be typed in.
  Severity: major | Source: Mozilla

Match 3: Login Fails if token is reset while waiting for a password.
  Severity: normal | Source: Mozilla

Match 4: [pwd-mngr] Password incorrectly stored
  Severity: minor | Source: Mozilla

Match 5: [pwd-mngr] Password incorrectly stored
  Severity: minor | Source: Mozilla

In [16]:
import sklearn
print(sklearn.__version__)

1.4.0

In [1]:
1+2

3

In [9]:
import numpy as np

# Save the embeddings matrix
np.save("../src/embeddings.npy", embeddings.toarray())

# Save the metadata needed to display results (aligned by row index with embeddings)
chunks_df[['bug_id', 'title', 'severity', 'resolution', 'status', 'source_dataset']].to_csv("../src/chunks_metadata.csv", index=False)

print("Saved embeddings and metadata.")

Saved embeddings and metadata.

In [1]:
import pandas as pd
chunks_df = pd.read_csv("../data/chunks_df.csv")
print(chunks_df.shape)

(56862, 8)

In [2]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer('all-MiniLM-L6-v2')
print("Model loaded")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Model loaded

In [ ]:
chunk_texts = chunks_df['chunk_text'].tolist()

embeddings = model.encode(
    chunk_texts,
    batch_size=64,
    show_progress_bar=True,
    convert_to_numpy=True
)

print("Embeddings shape:", embeddings.shape)

In [4]:
import time

start = time.time()
test_embeddings = model.encode(chunk_texts[:5], convert_to_numpy=True)
print("Took", time.time() - start, "seconds")
print(test_embeddings.shape)

Took 0.47360730171203613 seconds
(5, 384)

In [5]:
import time

start = time.time()
test_embeddings_1000 = model.encode(
    chunk_texts[:1000],
    batch_size=64,
    convert_to_numpy=True
)
print("Took", time.time() - start, "seconds")
print(test_embeddings_1000.shape)

Took 43.57127594947815 seconds
(1000, 384)

In [6]:
import numpy as np
import time

all_embeddings = []
chunk_size = 10000
total = len(chunk_texts)

for i in range(0, total, chunk_size):
    batch_texts = chunk_texts[i:i+chunk_size]
    start = time.time()
    batch_embeddings = model.encode(batch_texts, batch_size=64, convert_to_numpy=True)
    all_embeddings.append(batch_embeddings)
    print(f"Processed {i} to {min(i+chunk_size, total)} — took {time.time()-start:.1f}s")

embeddings = np.vstack(all_embeddings)
print("Final embeddings shape:", embeddings.shape)

Processed 0 to 10000 — took 487.7s
Processed 10000 to 20000 — took 472.8s
Processed 20000 to 30000 — took 457.5s
Processed 30000 to 40000 — took 504.3s
Processed 40000 to 50000 — took 457.9s
Processed 50000 to 56862 — took 315.1s
Final embeddings shape: (56862, 384)

In [8]:
import numpy as np

np.save("../src/embeddings_real.npy", embeddings)
print("Saved real embeddings:", embeddings.shape)

Saved real embeddings: (56862, 384)

In [9]:
print(chunks_df['source_dataset'].value_counts())

source_dataset
Apache     20443
Eclipse    19025
Mozilla    17394
Name: count, dtype: int64

In [12]:
query_vector = model.encode(["app crash on login"], convert_to_numpy=True)
similarities = cosine_similarity(query_vector, embeddings)[0]

# Add similarity scores to a copy of chunks_df for inspection
chunks_df['similarity'] = similarities

# Show top 5 per source_dataset separately
for source in ['Mozilla', 'Eclipse', 'Apache']:
    print(f"\n--- Top 3 in {source} ---")
    top = chunks_df[chunks_df['source_dataset'] == source].sort_values('similarity', ascending=False).head(3)
    for _, row in top.iterrows():
        print(f"{row['similarity']:.3f} | {row['title']}")

--- Top 3 in Mozilla ---
0.588 | [webgl] Null deref crash in gleRunVertexSubmitImmediate / mozilla::WebGLContext::DrawElements
0.547 | crash while doing nothing... [@ nsMsgCompose::OnSendNotPerformed]
0.545 | mozilla 0.8.1 crashes when I try to login into bugzilla

--- Top 3 in Eclipse ---
0.486 | Crash at startup
0.457 | Invalid login message accessibility
0.453 | improve feedback on startup railure

--- Top 3 in Apache ---
0.445 | Automation crashes player (a211) when repeatedly bouncing app
0.444 | DTD in sqlMapConfig doesn't get resolved when not connected to internet
0.413 | can't able to login to roller